"""Node dependency graph and asset locking (issue #142, task P5.1).

``ProjectGraph`` is a directed acyclic graph of ``Node`` objects keyed by
unique id.  Edges encode "depends on" relationships (e.g. the mix depends
on every audio node; the assemble depends on every video node and the mix).

Each ``Node`` supports ``lock()`` / ``unlock(reason)`` — a locked node
refuses ``generate()`` unless ``unlock(reason)`` was called with a
non-empty reason.  The lock state is persisted into the
``ProjectManifest`` so a rebuild can re-hydrate the graph with the same
lock state.

The graph is built from a :class:`~music_cli.studio.schemas.CreativePlan`
and validates that all dependency references resolve before it is
considered valid.  Topological ordering is deterministic: nodes within
the same dependency wave are sorted by id.
"""

from __future__ import annotations

from collections import defaultdict, deque
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from .schemas import CreativePlan, ProjectManifest

# ---------------------------------------------------------------------------
# Exceptions
# ---------------------------------------------------------------------------


class GraphError(RuntimeError):
    """The graph is invalid (cycle, missing dependency, etc.)."""


class GraphCycleError(GraphError):
    """A cycle was detected in the dependency graph."""


class GraphMissingDependency(GraphError):
    """A dependency references a node id that does not exist in the graph."""


class NodeLockedError(GraphError):
    """The node is locked and must be unlocked before generating."""


# ---------------------------------------------------------------------------
# Node
# ---------------------------------------------------------------------------


@dataclass
class Node:
    """A single node in the project graph.

    Attributes:
        id: Unique node identifier (e.g. ``"music-1"``, ``"mix"``).
        node_type: One of ``"music"``, ``"speech"``, ``"video"``,
            ``"mix"``, ``"assemble"``, ``"audio"``, ``"caption"``.
        prompt: Human-readable prompt or description for the node.
        depends_on: Ordered list of node ids this node depends on.
        output_path: Path to the generated output (set after generation).
        locked: Whether the node is currently locked (outputs read-only).
        lock_reason: The reason the node was unlocked last (empty when
            locked, set by :meth:`unlock`).
    """

    id: str
    node_type: str
    prompt: str = ""
    depends_on: list[str] = field(default_factory=list)
    output_path: str | None = None
    locked: bool = False
    lock_reason: str = ""

    # -- lifecycle ---------------------------------------------------------

    def generate(self, *args: Any, **kwargs: Any) -> Path:
        """Generate the node's output.

        Raises :class:`NodeLockedError` when the node is locked and no
        unlock reason is recorded.  Subclasses or callers may override
        this to provide actual generation logic.
        """
        if self.locked:
            raise NodeLockedError(
                f"node {self.id!r} is locked; call unlock(reason) before generating"
            )
        # Default: write a placeholder file.  Real nodes override.
        dest = Path(self.output_path) if self.output_path else None
        if dest is None:
            dest = Path(f"nodes/{self.id}.out")
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_text(f"generated by {self.id}", encoding="utf-8")
        self.output_path = str(dest)
        self.locked = True
        return dest

    def lock(self) -> None:
        """Mark the node as locked (outputs read-only)."""
        self.locked = True
        self.lock_reason = ""

    def unlock(self, reason: str) -> None:
        """Unlock the node with a non-empty reason.

        Args:
            reason: A human-readable explanation for why the node is
                being regenerated.  Must not be empty.

        Raises:
            ValueError: If ``reason`` is empty or whitespace.
        """
        if not reason or not reason.strip():
            raise ValueError("unlock requires a non-empty reason")
        self.locked = False
        self.lock_reason = reason.strip()

    def to_dict(self) -> dict[str, Any]:
        """Serialize the node for persistence in a manifest."""
        return {
            "id": self.id,
            "type": self.node_type,
            "prompt": self.prompt,
            "depends_on": list(self.depends_on),
            "output_path": self.output_path,
            "locked": self.locked,
            "lock_reason": self.lock_reason,
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> Node:
        """Reconstruct a node from a manifest record."""
        return cls(
            id=data["id"],
            node_type=data["type"],
            prompt=data.get("prompt", ""),
            depends_on=list(data.get("depends_on", [])),
            output_path=data.get("output_path"),
            locked=data.get("locked", False),
            lock_reason=data.get("lock_reason", ""),
        )


# ---------------------------------------------------------------------------
# ProjectGraph
# ---------------------------------------------------------------------------


@dataclass
class ProjectGraph:
    """A dependency graph for a creative project.

    The graph is built from a :class:`CreativePlan` and validates that
    all dependency references resolve before it is considered valid.
    Nodes are keyed by their ``id``.

    Example usage::

        graph = ProjectGraph.from_plan(plan)
        graph.validate()
        order = graph.topological_order()
        for node_id in order:
            await graph.nodes[node_id].generate()
    """

    nodes: dict[str, Node] = field(default_factory=dict)
    _edges: dict[str, set[str]] = field(default_factory=lambda: defaultdict(set))
    _plan_data: dict[str, Any] = field(default_factory=dict)

    # -- construction ------------------------------------------------------

    @classmethod
    def from_plan(cls, plan: CreativePlan) -> ProjectGraph:
        """Build a graph from a :class:`CreativePlan`.

        The plan's scenes, tracks, and shot_list are turned into nodes.
        Dependencies are inferred:

        - Every **mix** node depends on all **music** and **speech** nodes.
        - Every **assemble** node depends on all **video** nodes and the
          mix (if present).
        - Nodes with explicit ``depends_on`` in the plan override the
          defaults.

        Args:
            plan: A validated creative plan.

        Returns:
            A new ``ProjectGraph`` ready for validation.
        """
        graph = cls()
        plan_data = plan.to_dict()
        graph._plan_data = plan_data
        plan_id = plan_data.get("plan_id", "unknown")

        # Collect nodes by type from plan sections
        scene_nodes: list[Node] = []
        music_nodes: list[Node] = []
        speech_nodes: list[Node] = []
        video_nodes: list[Node] = []

        # Tracks → music nodes
        tracks = plan_data.get("tracks") or []
        for idx, track in enumerate(tracks, start=1):
            if isinstance(track, dict):
                prompt = track.get("prompt") or track.get("lyrics") or ""
            else:
                prompt = str(track) if track else ""
            node = Node(
                id=f"music-{idx}",
                node_type="music",
                prompt=str(prompt),
            )
            music_nodes.append(node)

        # Narration from scenes → speech nodes
        scenes = plan_data.get("scenes") or plan_data.get("shot_list") or []
        speech_idx = 1
        for scene in scenes:
            if not isinstance(scene, dict):
                continue
            text = scene.get("description") or scene.get("prompt") or ""
            if text:
                node = Node(
                    id=f"speech-{speech_idx}",
                    node_type="speech",
                    prompt=str(text),
                )
                speech_nodes.append(node)
                speech_idx += 1

        # Video nodes from scenes/shot_list
        for idx, scene in enumerate(scenes, start=1):
            if not isinstance(scene, dict):
                continue
            visual = scene.get("visual_prompt") or scene.get("description") or ""
            node = Node(
                id=f"scene-{idx}",
                node_type="video",
                prompt=str(visual),
            )
            video_nodes.append(node)

        # Add all nodes to the graph
        all_nodes = music_nodes + speech_nodes + video_nodes
        for node in all_nodes:
            graph.nodes[node.id] = node
            graph._edges[node.id]  # ensure entry exists

        # Add mix node (depends on all music nodes only)
        if music_nodes:
            mix_node = Node(
                id="mix",
                node_type="mix",
                prompt="Mix audio tracks",
                depends_on=[n.id for n in music_nodes],
            )
            graph.nodes["mix"] = mix_node
            graph._edges["mix"] = set(n.id for n in music_nodes)

        # Add assemble node (depends on all video nodes + mix if present)
        # Only created when there are video nodes (scenes/shot_list exist)
        if video_nodes:
            assemble_deps: list[str] = [n.id for n in video_nodes]
            if "mix" in graph.nodes:
                assemble_deps.append("mix")
            assemble_node = Node(
                id="assemble",
                node_type="assemble",
                prompt="Assemble video scenes with audio",
                depends_on=assemble_deps,
            )
            graph.nodes["assemble"] = assemble_node
            graph._edges["assemble"] = set(assemble_deps)

        return graph

    @classmethod
    def from_manifest(
        cls,
        manifest: ProjectManifest | dict[str, Any],
    ) -> ProjectGraph:
        """Re-hydrate a graph from a ``ProjectManifest``.

        Args:
            manifest: A manifest dict or ``ProjectManifest`` instance.

        Returns:
            A ``ProjectGraph`` with nodes restored from the manifest.
        """
        if isinstance(manifest, ProjectManifest):
            data = manifest.to_dict()
        else:
            data = manifest

        graph = cls()
        graph._plan_data = data.get("plan", {})
        nodes_data = data.get("nodes", [])

        for node_data in nodes_data:
            if not isinstance(node_data, dict):
                continue
            node = Node.from_dict(node_data)
            graph.nodes[node.id] = node
            graph._edges[node.id] = set(node.depends_on)

        return graph

    # -- validation --------------------------------------------------------

    def validate(self) -> list[str]:
        """Validate the graph structure.

        Checks:

        1. Every node has a unique id.
        2. Every dependency references an existing node.
        3. No cycles exist.

        Returns:
            A list of error strings.  Empty means valid.
        """
        errors: list[str] = []

        # 1. Unique ids
        seen_ids: set[str] = set()
        for nid in self.nodes:
            if nid in seen_ids:
                errors.append(f"duplicate node id: {nid!r}")
            seen_ids.add(nid)

        # 2. Resolve dependencies
        for nid, node in self.nodes.items():
            for dep in node.depends_on:
                if dep not in self.nodes:
                    errors.append(f"node {nid!r} depends on unknown node {dep!r}")

        # 3. Cycle detection
        cycle_errors = self._detect_cycles()
        errors.extend(cycle_errors)

        return errors

    def _detect_cycles(self) -> list[str]:
        """Detect cycles using Kahn's algorithm.

        Returns a list of cycle error strings.  Empty means no cycles.
        """
        # Build in-degree map
        in_degree: dict[str, int] = dict.fromkeys(self.nodes, 0)
        for nid, deps in self._edges.items():
            for dep in deps:
                if dep in in_degree:
                    in_degree[nid] = in_degree.get(nid, 0)

        # Recount properly
        in_degree = dict.fromkeys(self.nodes, 0)
        for nid in self.nodes:
            for dep in self._edges.get(nid, set()):
                if dep in self.nodes:
                    in_degree[nid] = in_degree.get(nid, 0) + 1

        # Actually we need: edges go FROM dependent TO dependency
        # So in_degree[node] = number of nodes that depend on this node?
        # No — for topological sort, in_degree[node] = number of
        # dependencies this node has (edges pointing to it).
        # Actually the _edges[nid] = set of nodes that nid depends ON.
        # So for topo sort: in_degree[nid] = len(_edges[nid])
        in_degree = {}
        for nid in self.nodes:
            in_degree[nid] = len(self._edges.get(nid, set()) & set(self.nodes))

        queue: deque[str] = deque()
        for nid in sorted(self.nodes):
            if in_degree[nid] == 0:
                queue.append(nid)

        visited_count = 0
        while queue:
            nid = queue.popleft()
            visited_count += 1
            # Find all nodes that depend on nid
            for other_nid, deps in self._edges.items():
                if nid in deps and other_nid in self.nodes:
                    in_degree[other_nid] -= 1
                    if in_degree[other_nid] == 0:
                        queue.append(other_nid)

        if visited_count != len(self.nodes):
            return [f"dependency cycle detected among {visited_count}/{len(self.nodes)} nodes"]
        return []

    # -- topological order -------------------------------------------------

    def topological_order(self) -> list[str]:
        """Return a deterministic topological ordering of node ids.

        Nodes are ordered so that every node appears after all its
        dependencies.  Within the same dependency wave, nodes are sorted
        by id for determinism.

        Returns:
            A list of node ids in topological order.

        Raises:
            GraphCycleError: If the graph contains a cycle.
        """
        errors = self.validate()
        if errors:
            cycle_errors = [e for e in errors if "cycle" in e.lower()]
            if cycle_errors:
                raise GraphCycleError(cycle_errors[0])
            raise GraphError("; ".join(errors))

        # Kahn's algorithm with sorted queue for determinism
        in_degree: dict[str, int] = {}
        for nid in self.nodes:
            in_degree[nid] = len(self._edges.get(nid, set()) & set(self.nodes))

        # Use a sorted list as a priority queue for determinism
        ready = sorted(nid for nid, deg in in_degree.items() if deg == 0)
        order: list[str] = []

        while ready:
            nid = ready.pop(0)  # take the smallest id
            order.append(nid)
            # Find nodes that depend on nid
            next_ready: list[str] = []
            for other_nid, deps in self._edges.items():
                if nid in deps and other_nid in self.nodes:
                    in_degree[other_nid] -= 1
                    if in_degree[other_nid] == 0:
                        next_ready.append(other_nid)
            # Insert new ready nodes in sorted position
            for nr in sorted(next_ready):
                # Insert in sorted order
                inserted = False
                for i, existing in enumerate(ready):
                    if nr < existing:
                        ready.insert(i, nr)
                        inserted = True
                        break
                if not inserted:
                    ready.append(nr)

        return order

    # -- lock management ---------------------------------------------------

    def lock_node(self, node_id: str, reason: str = "") -> None:
        """Lock a node by id.

        Args:
            node_id: The node to lock.
            reason: Optional reason (stored for audit).

        Raises:
            KeyError: If the node id does not exist.
        """
        if node_id not in self.nodes:
            raise KeyError(f"unknown node: {node_id!r}")
        self.nodes[node_id].lock()

    def unlock_node(self, node_id: str, reason: str) -> None:
        """Unlock a node by id with a reason.

        Args:
            node_id: The node to unlock.
            reason: A non-empty explanation for the unlock.

        Raises:
            KeyError: If the node id does not exist.
            ValueError: If reason is empty.
        """
        if node_id not in self.nodes:
            raise KeyError(f"unknown node: {node_id!r}")
        self.nodes[node_id].unlock(reason)

    def is_locked(self, node_id: str) -> bool:
        """Check whether a node is locked.

        Args:
            node_id: The node to check.

        Returns:
            True if the node is locked.

        Raises:
            KeyError: If the node id does not exist.
        """
        if node_id not in self.nodes:
            raise KeyError(f"unknown node: {node_id!r}")
        return self.nodes[node_id].locked

    # -- manifest persistence ----------------------------------------------

    def persist_locks(self, manifest: dict[str, Any]) -> dict[str, Any]:
        """Persist the current lock state into a manifest dict.

        Updates the ``locked_nodes`` list in the manifest to reflect
        the current state of all nodes in the graph.

        Args:
            manifest: A manifest dict (modified in place).

        Returns:
            The updated manifest dict.
        """
        locked = [nid for nid, node in sorted(self.nodes.items()) if node.locked]
        manifest["locked_nodes"] = locked

        # Also update individual node lock states in the nodes list
        if "nodes" in manifest and isinstance(manifest["nodes"], list):
            for manifest_node in manifest["nodes"]:
                if isinstance(manifest_node, dict):
                    nid = manifest_node.get("id")
                    if nid in self.nodes:
                        manifest_node["locked"] = self.nodes[nid].locked
                        manifest_node["lock_reason"] = self.nodes[nid].lock_reason

        return manifest

    def load_locks(self, manifest: dict[str, Any]) -> None:
        """Load lock state from a manifest dict into the graph.

        Args:
            manifest: A manifest dict with ``locked_nodes`` and/or
                ``nodes`` entries.
        """
        locked_set: set[str] = set(manifest.get("locked_nodes", []))

        for nid, node in self.nodes.items():
            if nid in locked_set:
                node.locked = True
                node.lock_reason = ""
            else:
                node.locked = False
                node.lock_reason = ""

        # Also apply per-node lock state from nodes list
        for manifest_node in manifest.get("nodes", []):
            if isinstance(manifest_node, dict):
                nid = manifest_node.get("id")
                if nid in self.nodes:
                    node = self.nodes[nid]
                    node.locked = bool(manifest_node.get("locked", False))
                    node.lock_reason = manifest_node.get("lock_reason", "")

    # -- edges -------------------------------------------------------------

    def add_edge(self, from_id: str, to_id: str) -> None:
        """Add a dependency edge: ``from_id`` depends on ``to_id``.

        Args:
            from_id: The dependent node.
            to_id: The dependency node.

        Raises:
            KeyError: If either node id does not exist.
        """
        if from_id not in self.nodes:
            raise KeyError(f"unknown node: {from_id!r}")
        if to_id not in self.nodes:
            raise KeyError(f"unknown node: {to_id!r}")
        self._edges[from_id].add(to_id)

    def get_dependencies(self, node_id: str) -> set[str]:
        """Return the set of node ids that ``node_id`` depends on.

        Args:
            node_id: The node to query.

        Returns:
            A set of dependency node ids.

        Raises:
            KeyError: If the node id does not exist.
        """
        if node_id not in self.nodes:
            raise KeyError(f"unknown node: {node_id!r}")
        return set(self._edges.get(node_id, set()) & set(self.nodes))

    def get_dependents(self, node_id: str) -> set[str]:
        """Return the set of nodes that depend on ``node_id``.

        Args:
            node_id: The node to query.

        Returns:
            A set of dependent node ids.

        Raises:
            KeyError: If the node id does not exist.
        """
        if node_id not in self.nodes:
            raise KeyError(f"unknown node: {node_id!r}")
        dependents = set()
        for other_nid, deps in self._edges.items():
            if node_id in deps and other_nid in self.nodes:
                dependents.add(other_nid)
        return dependents

    # -- serialization -----------------------------------------------------

    def to_dict(self) -> dict[str, Any]:
        """Serialize the graph to a dict suitable for manifest storage."""
        return {
            "nodes": {nid: node.to_dict() for nid, node in sorted(self.nodes.items())},
            "edges": {nid: sorted(deps) for nid, deps in sorted(self._edges.items())},
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> ProjectGraph:
        """Reconstruct a graph from a serialized dict."""
        graph = cls()
        nodes_data = data.get("nodes", {})
        for nid, node_data in nodes_data.items():
            node = Node.from_dict(node_data)
            graph.nodes[nid] = node
            graph._edges[nid] = set(node.depends_on)
        return graph
